general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[font]
size = 10 
builtin_box_drawing = true

[font.bold]
family = "BlexMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "SemiBold Italic"


[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"
