#!/bin/bash

model=$(cat /sys/devices/virtual/dmi/id/product_family)

if [ "$model" == "ThinkPad T490" ]; then
  intern=eDP-1
  extern=HDMI-1-0
elif [ "$model" == "Nitro 5" ]; then
  intern=eDP-1-1
  extern=HDMI-0
else
  # Default fallback
  intern=eDP-1
  extern=HDMI-1
fi

if xrandr | grep "$extern disconnected"; then
  xrandr --output "$intern" --auto --primary
else
  xrandr --output "$intern" --auto --primary --right-of "$extern" --output "$extern" --auto
fi
